### ISSUE TITLE
Add data of safety

### ISSUE THREAD

**Issue by YuriTuri** [yoichiojima-2/sign-to-migrate#4]
Please add data for comparing safety 
- Crime rate
- Homicide rate
- Theft rate
- terrorism index 
- global peace index 
- Word risk index
- Safe cities index

**Comment by yoichiojima-2** [comment]
homicide rate may be found here: https://www.unodc.org/unodc/en/data-and-analysis/global-study-on-homicide-2019.html?utm_source=chatgpt.com

**Comment by yoichiojima-2** [comment]
i assumed the purpose here is to get a sence of how safe the cities are. numbeo offeres safety index as well as cost of living: https://www.numbeo.com/crime/rankings_current.jsp?displayColumn=1

**Comment by yoichiojima-2** [comment]
think i should take a look what else numbeo offers.. 🧐
